### ISSUE TITLE
Styling Issue

### ISSUE THREAD

**Issue by SkyanSam** [team4099/InfiniteRecharge-2020#27]
Just leaving this here to jot down styling notes and errors.

**Comment by SkyanSam** [comment]
01/13/20
Drive: Successful
Climber & Shooter: Style errors in lib but not neccessary to fix.
 E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSmartMotorController.kt: (54, 35): Parameter 'periodMs' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (187, 13): Parameter 'value' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (190, 13): Parameter 'value' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (235, 13): Parameter 'value' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (244, 13): Parameter 'value' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (338, 13): Parameter 'value' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (348, 13): Parameter 'value' is never used
w: E:\school\team4099\infiniterecharge\InfiniteRecharge-2020\src\main\kotlin\com\team4099\lib\motorcontroller\GenericSparkMax.kt: (358, 13): Parameter 'value' is never used

Vision: Successful

ill stop here cause I realized im not code reviewer lol

**Comment by aidangoettsch** [comment]
> ill stop here cause I realized im not code reviewer lol

Code review from anyone is appreciated! We're not going to use GenericMotorController and related classes this season (there's a bit too much left to do to make sure it's truly stable), so I've opened #30 to remove it for now.
